// Generated by gencpp from file kalman/radar_mobileye_data_multi.msg
// DO NOT EDIT!


#ifndef KALMAN_MESSAGE_RADAR_MOBILEYE_DATA_MULTI_H
#define KALMAN_MESSAGE_RADAR_MOBILEYE_DATA_MULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kalman/radar_mobileye_data.h>

namespace kalman
{
template <class ContainerAllocator>
struct radar_mobileye_data_multi_
{
  typedef radar_mobileye_data_multi_<ContainerAllocator> Type;

  radar_mobileye_data_multi_()
    : objs()  {
    }
  radar_mobileye_data_multi_(const ContainerAllocator& _alloc)
    : objs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kalman::radar_mobileye_data_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::kalman::radar_mobileye_data_<ContainerAllocator> >::other >  _objs_type;
  _objs_type objs;




  typedef boost::shared_ptr< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> const> ConstPtr;

}; // struct radar_mobileye_data_multi_

typedef ::kalman::radar_mobileye_data_multi_<std::allocator<void> > radar_mobileye_data_multi;

typedef boost::shared_ptr< ::kalman::radar_mobileye_data_multi > radar_mobileye_data_multiPtr;
typedef boost::shared_ptr< ::kalman::radar_mobileye_data_multi const> radar_mobileye_data_multiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kalman::radar_mobileye_data_multi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kalman

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'kalman': ['/home/michael/Desktop/Intell_driving/ROS_Intell_Driving/src/kalman/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f82daca84d74de475a3e5f540c588e8";
  }

  static const char* value(const ::kalman::radar_mobileye_data_multi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f82daca84d74de4ULL;
  static const uint64_t static_value2 = 0x75a3e5f540c588e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kalman/radar_mobileye_data_multi";
  }

  static const char* value(const ::kalman::radar_mobileye_data_multi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_mobileye_data[] objs\n\
\n\
================================================================================\n\
MSG: kalman/radar_mobileye_data\n\
uint32 timestamp\n\
uint8 ID\n\
float32 radar_DistX\n\
float32 radar_DistY\n\
float32 radar_VrelX\n\
float32 radar_VrelY\n\
float32 radar_ArelX\n\
float32 radar_ArelY\n\
float32 mobileye_DistX\n\
float32 mobileye_DistY\n\
float32 mobileye_VrelX\n\
float32 mobileye_ArelX\n\
float32 fusion_DistX\n\
float32 fusion_DistY\n\
float32 fusion_VrelX\n\
float32 fusion_VrelY\n\
float32 fusion_ArelX\n\
float32 fusion_ArelY\n\
float32 fusion_Length\n\
float32 fusion_Width\n\
float32 mobileye_Width\n\
float32 mobileye_Length\n\
uint8 fusion_flag\n\
";
  }

  static const char* value(const ::kalman::radar_mobileye_data_multi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_mobileye_data_multi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kalman::radar_mobileye_data_multi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kalman::radar_mobileye_data_multi_<ContainerAllocator>& v)
  {
    s << indent << "objs[]" << std::endl;
    for (size_t i = 0; i < v.objs.size(); ++i)
    {
      s << indent << "  objs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kalman::radar_mobileye_data_<ContainerAllocator> >::stream(s, indent + "    ", v.objs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KALMAN_MESSAGE_RADAR_MOBILEYE_DATA_MULTI_H
