(cl:in-package milradar-msg)
(cl:export '(ID-VAL
          ID
          TIMESTAMP-VAL
          TIMESTAMP
          DISTX-VAL
          DISTX
          DISTY-VAL
          DISTY
          VRELX-VAL
          VRELX
          VRELY-VAL
          VRELY
          RCS-VAL
          RCS
          DYNPROP-VAL
          DYNPROP
          ORIENTATION_RMS-VAL
          ORIENTATION_RMS
          MEASSTATE-VAL
          MEASSTATE
          PROBOFEXIST-VAL
          PROBOFEXIST
          ARELX-VAL
          ARELX
          ARELY-VAL
          ARELY
          CLASS-VAL
          CLASS
          ORIENTATIONANGEL-VAL
          ORIENTATIONANGEL
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
))