# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from canbus/candata_multi.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import canbus.msg

class candata_multi(genpy.Message):
  _md5sum = "7b71a82993b1f36499df06dc83eac42a"
  _type = "canbus/candata_multi"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """candata[] frame

================================================================================
MSG: canbus/candata
uint32 id
uint32 timestamp
uint8[8] data
"""
  __slots__ = ['frame']
  _slot_types = ['canbus/candata[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(candata_multi, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frame is None:
        self.frame = []
    else:
      self.frame = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.frame)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame:
        _x = val1
        buff.write(_struct_2I.pack(_x.id, _x.timestamp))
        _x = val1.data
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(_struct_8B.pack(*_x))
        else:
          buff.write(_struct_8s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.frame is None:
        self.frame = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame = []
      for i in range(0, length):
        val1 = canbus.msg.candata()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.timestamp,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 8
        val1.data = str[start:end]
        self.frame.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.frame)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame:
        _x = val1
        buff.write(_struct_2I.pack(_x.id, _x.timestamp))
        _x = val1.data
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(_struct_8B.pack(*_x))
        else:
          buff.write(_struct_8s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.frame is None:
        self.frame = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame = []
      for i in range(0, length):
        val1 = canbus.msg.candata()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.timestamp,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 8
        val1.data = str[start:end]
        self.frame.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8B = struct.Struct("<8B")
_struct_8s = struct.Struct("<8s")
_struct_2I = struct.Struct("<2I")
