(cl:in-package mobileye-msg)
(cl:export '(ID-VAL
          ID
          TIMESTAMP-VAL
          TIMESTAMP
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          BLINKER-VAL
          BLINKER
          CUTSTATE-VAL
          CUTSTATE
          VRELX-VAL
          VRELX
          MTYPE-VAL
          MTYPE
          STATUS-VAL
          STATUS
          BRAKE-VAL
          BRAKE
          VALID-VAL
          VALID
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          AGE-VAL
          AGE
          OBSLANE-VAL
          OBSLANE
          CIPV-VAL
          CIPV
          ANGLERATE-VAL
          ANGLERATE
          SCALECHANGE-VAL
          SCALECHANGE
          ARELX-VAL
          ARELX
          ANGLE-VAL
          ANGLE
          REPLACED-VAL
          REPLACED
))