(cl:in-package Mobileye-msg)
(cl:export '(ID-VAL
          ID
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          BLINKER-VAL
          BLINKER
          CUTSTATE-VAL
          CUTSTATE
          VRELX-VAL
          VRELX
          MTYPE-VAL
          MTYPE
          STATUS-VAL
          STATUS
          BRAKE-VAL
          BRAKE
          VALID-VAL
          VALID
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          AGE-VAL
          AGE
          OBSLANE-VAL
          OBSLANE
          CIPV-VAL
          CIPV
          ANGLERATE-VAL
          ANGLERATE
          SCALECHANGE-VAL
          SCALECHANGE
          ACCELX-VAL
          ACCELX
          ANGLE-VAL
          ANGLE
          REPLACED-VAL
          REPLACED
))