# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from milradar/obj208_multi.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import milradar.msg

class obj208_multi(genpy.Message):
  _md5sum = "f98d0ef87b339f5337f23f3835cf534b"
  _type = "milradar/obj208_multi"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """obj208[] objs

================================================================================
MSG: milradar/obj208
uint16 ID
uint32 timestamp
float32 DistX
float32 DistY
uint8 index
float32 VrelX
float32 VrelY
float32 RCS
float32 Lifetime
"""
  __slots__ = ['objs']
  _slot_types = ['milradar/obj208[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       objs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obj208_multi, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.objs is None:
        self.objs = []
    else:
      self.objs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.objs)
      buff.write(_struct_I.pack(length))
      for val1 in self.objs:
        _x = val1
        buff.write(_struct_HI2fB4f.pack(_x.ID, _x.timestamp, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.objs is None:
        self.objs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objs = []
      for i in range(0, length):
        val1 = milradar.msg.obj208()
        _x = val1
        start = end
        end += 31
        (_x.ID, _x.timestamp, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime,) = _struct_HI2fB4f.unpack(str[start:end])
        self.objs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.objs)
      buff.write(_struct_I.pack(length))
      for val1 in self.objs:
        _x = val1
        buff.write(_struct_HI2fB4f.pack(_x.ID, _x.timestamp, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.objs is None:
        self.objs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objs = []
      for i in range(0, length):
        val1 = milradar.msg.obj208()
        _x = val1
        start = end
        end += 31
        (_x.ID, _x.timestamp, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime,) = _struct_HI2fB4f.unpack(str[start:end])
        self.objs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_HI2fB4f = struct.Struct("<HI2fB4f")
