# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from milradar/obj208.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class obj208(genpy.Message):
  _md5sum = "877e2a00fa1ceb509828c3b1f5ccd38a"
  _type = "milradar/obj208"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 ID
float32 DistX
float32 DistY
uint8 index
float32 VrelX
float32 VrelY
float32 RCS
float32 Lifetime
"""
  __slots__ = ['ID','DistX','DistY','index','VrelX','VrelY','RCS','Lifetime']
  _slot_types = ['uint16','float32','float32','uint8','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,DistX,DistY,index,VrelX,VrelY,RCS,Lifetime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obj208, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.DistX is None:
        self.DistX = 0.
      if self.DistY is None:
        self.DistY = 0.
      if self.index is None:
        self.index = 0
      if self.VrelX is None:
        self.VrelX = 0.
      if self.VrelY is None:
        self.VrelY = 0.
      if self.RCS is None:
        self.RCS = 0.
      if self.Lifetime is None:
        self.Lifetime = 0.
    else:
      self.ID = 0
      self.DistX = 0.
      self.DistY = 0.
      self.index = 0
      self.VrelX = 0.
      self.VrelY = 0.
      self.RCS = 0.
      self.Lifetime = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_H2fB4f.pack(_x.ID, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.ID, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime,) = _struct_H2fB4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_H2fB4f.pack(_x.ID, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.ID, _x.DistX, _x.DistY, _x.index, _x.VrelX, _x.VrelY, _x.RCS, _x.Lifetime,) = _struct_H2fB4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_H2fB4f = struct.Struct("<H2fB4f")
