// Generated by gencpp from file milradar/obj208_multi.msg
// DO NOT EDIT!


#ifndef MILRADAR_MESSAGE_OBJ208_MULTI_H
#define MILRADAR_MESSAGE_OBJ208_MULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <milradar/obj208.h>

namespace milradar
{
template <class ContainerAllocator>
struct obj208_multi_
{
  typedef obj208_multi_<ContainerAllocator> Type;

  obj208_multi_()
    : objs()  {
    }
  obj208_multi_(const ContainerAllocator& _alloc)
    : objs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::milradar::obj208_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::milradar::obj208_<ContainerAllocator> >::other >  _objs_type;
  _objs_type objs;




  typedef boost::shared_ptr< ::milradar::obj208_multi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::milradar::obj208_multi_<ContainerAllocator> const> ConstPtr;

}; // struct obj208_multi_

typedef ::milradar::obj208_multi_<std::allocator<void> > obj208_multi;

typedef boost::shared_ptr< ::milradar::obj208_multi > obj208_multiPtr;
typedef boost::shared_ptr< ::milradar::obj208_multi const> obj208_multiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::milradar::obj208_multi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::milradar::obj208_multi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace milradar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'milradar': ['/home/silentroar/Desktop/ROS_Intell_Driving/src/milradar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::milradar::obj208_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::milradar::obj208_multi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milradar::obj208_multi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milradar::obj208_multi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milradar::obj208_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milradar::obj208_multi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::milradar::obj208_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f98d0ef87b339f5337f23f3835cf534b";
  }

  static const char* value(const ::milradar::obj208_multi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf98d0ef87b339f53ULL;
  static const uint64_t static_value2 = 0x37f23f3835cf534bULL;
};

template<class ContainerAllocator>
struct DataType< ::milradar::obj208_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "milradar/obj208_multi";
  }

  static const char* value(const ::milradar::obj208_multi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::milradar::obj208_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obj208[] objs\n\
\n\
================================================================================\n\
MSG: milradar/obj208\n\
uint16 ID\n\
uint32 timestamp\n\
float32 DistX\n\
float32 DistY\n\
uint8 index\n\
float32 VrelX\n\
float32 VrelY\n\
float32 RCS\n\
float32 Lifetime\n\
";
  }

  static const char* value(const ::milradar::obj208_multi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::milradar::obj208_multi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obj208_multi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::milradar::obj208_multi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::milradar::obj208_multi_<ContainerAllocator>& v)
  {
    s << indent << "objs[]" << std::endl;
    for (size_t i = 0; i < v.objs.size(); ++i)
    {
      s << indent << "  objs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::milradar::obj208_<ContainerAllocator> >::stream(s, indent + "    ", v.objs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MILRADAR_MESSAGE_OBJ208_MULTI_H
