// Generated by gencpp from file milradar/obj408.msg
// DO NOT EDIT!


#ifndef MILRADAR_MESSAGE_OBJ408_H
#define MILRADAR_MESSAGE_OBJ408_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace milradar
{
template <class ContainerAllocator>
struct obj408_
{
  typedef obj408_<ContainerAllocator> Type;

  obj408_()
    : ID(0)
    , timestamp(0)
    , DistX(0.0)
    , DistY(0.0)
    , VrelX(0.0)
    , VrelY(0.0)
    , RCS(0.0)
    , DynProp(0)
    , Orientation_rms(0)
    , MeasState(0)
    , ProbOfExist(0)
    , ArelX(0.0)
    , ArelY(0.0)
    , Class(0)
    , OrientationAngel(0.0)
    , Length(0.0)
    , Width(0.0)  {
    }
  obj408_(const ContainerAllocator& _alloc)
    : ID(0)
    , timestamp(0)
    , DistX(0.0)
    , DistY(0.0)
    , VrelX(0.0)
    , VrelY(0.0)
    , RCS(0.0)
    , DynProp(0)
    , Orientation_rms(0)
    , MeasState(0)
    , ProbOfExist(0)
    , ArelX(0.0)
    , ArelY(0.0)
    , Class(0)
    , OrientationAngel(0.0)
    , Length(0.0)
    , Width(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _DistX_type;
  _DistX_type DistX;

   typedef float _DistY_type;
  _DistY_type DistY;

   typedef float _VrelX_type;
  _VrelX_type VrelX;

   typedef float _VrelY_type;
  _VrelY_type VrelY;

   typedef float _RCS_type;
  _RCS_type RCS;

   typedef uint8_t _DynProp_type;
  _DynProp_type DynProp;

   typedef uint8_t _Orientation_rms_type;
  _Orientation_rms_type Orientation_rms;

   typedef uint8_t _MeasState_type;
  _MeasState_type MeasState;

   typedef uint8_t _ProbOfExist_type;
  _ProbOfExist_type ProbOfExist;

   typedef float _ArelX_type;
  _ArelX_type ArelX;

   typedef float _ArelY_type;
  _ArelY_type ArelY;

   typedef uint8_t _Class_type;
  _Class_type Class;

   typedef float _OrientationAngel_type;
  _OrientationAngel_type OrientationAngel;

   typedef float _Length_type;
  _Length_type Length;

   typedef float _Width_type;
  _Width_type Width;




  typedef boost::shared_ptr< ::milradar::obj408_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::milradar::obj408_<ContainerAllocator> const> ConstPtr;

}; // struct obj408_

typedef ::milradar::obj408_<std::allocator<void> > obj408;

typedef boost::shared_ptr< ::milradar::obj408 > obj408Ptr;
typedef boost::shared_ptr< ::milradar::obj408 const> obj408ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::milradar::obj408_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::milradar::obj408_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace milradar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'milradar': ['/home/silentroar/Desktop/ROS_Intell_Driving/src/milradar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::milradar::obj408_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::milradar::obj408_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milradar::obj408_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milradar::obj408_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milradar::obj408_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milradar::obj408_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::milradar::obj408_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6746331b89c775f9d4d284533d0ef80d";
  }

  static const char* value(const ::milradar::obj408_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6746331b89c775f9ULL;
  static const uint64_t static_value2 = 0xd4d284533d0ef80dULL;
};

template<class ContainerAllocator>
struct DataType< ::milradar::obj408_<ContainerAllocator> >
{
  static const char* value()
  {
    return "milradar/obj408";
  }

  static const char* value(const ::milradar::obj408_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::milradar::obj408_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
uint32 timestamp\n\
float32 DistX\n\
float32 DistY\n\
float32 VrelX\n\
float32 VrelY\n\
float32 RCS\n\
uint8 DynProp\n\
uint8 Orientation_rms\n\
uint8 MeasState\n\
uint8 ProbOfExist\n\
float32 ArelX\n\
float32 ArelY\n\
uint8 Class\n\
float32 OrientationAngel\n\
float32 Length\n\
float32 Width\n\
";
  }

  static const char* value(const ::milradar::obj408_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::milradar::obj408_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.timestamp);
      stream.next(m.DistX);
      stream.next(m.DistY);
      stream.next(m.VrelX);
      stream.next(m.VrelY);
      stream.next(m.RCS);
      stream.next(m.DynProp);
      stream.next(m.Orientation_rms);
      stream.next(m.MeasState);
      stream.next(m.ProbOfExist);
      stream.next(m.ArelX);
      stream.next(m.ArelY);
      stream.next(m.Class);
      stream.next(m.OrientationAngel);
      stream.next(m.Length);
      stream.next(m.Width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obj408_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::milradar::obj408_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::milradar::obj408_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "DistX: ";
    Printer<float>::stream(s, indent + "  ", v.DistX);
    s << indent << "DistY: ";
    Printer<float>::stream(s, indent + "  ", v.DistY);
    s << indent << "VrelX: ";
    Printer<float>::stream(s, indent + "  ", v.VrelX);
    s << indent << "VrelY: ";
    Printer<float>::stream(s, indent + "  ", v.VrelY);
    s << indent << "RCS: ";
    Printer<float>::stream(s, indent + "  ", v.RCS);
    s << indent << "DynProp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.DynProp);
    s << indent << "Orientation_rms: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Orientation_rms);
    s << indent << "MeasState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MeasState);
    s << indent << "ProbOfExist: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ProbOfExist);
    s << indent << "ArelX: ";
    Printer<float>::stream(s, indent + "  ", v.ArelX);
    s << indent << "ArelY: ";
    Printer<float>::stream(s, indent + "  ", v.ArelY);
    s << indent << "Class: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Class);
    s << indent << "OrientationAngel: ";
    Printer<float>::stream(s, indent + "  ", v.OrientationAngel);
    s << indent << "Length: ";
    Printer<float>::stream(s, indent + "  ", v.Length);
    s << indent << "Width: ";
    Printer<float>::stream(s, indent + "  ", v.Width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MILRADAR_MESSAGE_OBJ408_H
