// Generated by gencpp from file mobileye/mobileye_TSR_multi.msg
// DO NOT EDIT!


#ifndef MOBILEYE_MESSAGE_MOBILEYE_TSR_MULTI_H
#define MOBILEYE_MESSAGE_MOBILEYE_TSR_MULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mobileye/mobileye_TSR.h>

namespace mobileye
{
template <class ContainerAllocator>
struct mobileye_TSR_multi_
{
  typedef mobileye_TSR_multi_<ContainerAllocator> Type;

  mobileye_TSR_multi_()
    : TSRs()  {
    }
  mobileye_TSR_multi_(const ContainerAllocator& _alloc)
    : TSRs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mobileye::mobileye_TSR_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mobileye::mobileye_TSR_<ContainerAllocator> >::other >  _TSRs_type;
  _TSRs_type TSRs;




  typedef boost::shared_ptr< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> const> ConstPtr;

}; // struct mobileye_TSR_multi_

typedef ::mobileye::mobileye_TSR_multi_<std::allocator<void> > mobileye_TSR_multi;

typedef boost::shared_ptr< ::mobileye::mobileye_TSR_multi > mobileye_TSR_multiPtr;
typedef boost::shared_ptr< ::mobileye::mobileye_TSR_multi const> mobileye_TSR_multiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileye::mobileye_TSR_multi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobileye

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mobileye': ['/home/silentroar/Desktop/ROS_Intell_Driving/src/mobileye/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f82b8888a7d5b24d3c3ff243115b7ee5";
  }

  static const char* value(const ::mobileye::mobileye_TSR_multi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf82b8888a7d5b24dULL;
  static const uint64_t static_value2 = 0x3c3ff243115b7ee5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye/mobileye_TSR_multi";
  }

  static const char* value(const ::mobileye::mobileye_TSR_multi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye_TSR[] TSRs\n\
\n\
================================================================================\n\
MSG: mobileye/mobileye_TSR\n\
uint8 MType\n\
uint8 SupType\n\
float32 PosX\n\
float32 PosY\n\
float32 PosZ\n\
uint8 FilterType\n\
";
  }

  static const char* value(const ::mobileye::mobileye_TSR_multi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TSRs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mobileye_TSR_multi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileye::mobileye_TSR_multi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileye::mobileye_TSR_multi_<ContainerAllocator>& v)
  {
    s << indent << "TSRs[]" << std::endl;
    for (size_t i = 0; i < v.TSRs.size(); ++i)
    {
      s << indent << "  TSRs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mobileye::mobileye_TSR_<ContainerAllocator> >::stream(s, indent + "    ", v.TSRs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILEYE_MESSAGE_MOBILEYE_TSR_MULTI_H
