// Generated by gencpp from file canbus/candata_multi.msg
// DO NOT EDIT!


#ifndef CANBUS_MESSAGE_CANDATA_MULTI_H
#define CANBUS_MESSAGE_CANDATA_MULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <canbus/candata.h>

namespace canbus
{
template <class ContainerAllocator>
struct candata_multi_
{
  typedef candata_multi_<ContainerAllocator> Type;

  candata_multi_()
    : frame()  {
    }
  candata_multi_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::canbus::candata_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::canbus::candata_<ContainerAllocator> >::other >  _frame_type;
  _frame_type frame;




  typedef boost::shared_ptr< ::canbus::candata_multi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canbus::candata_multi_<ContainerAllocator> const> ConstPtr;

}; // struct candata_multi_

typedef ::canbus::candata_multi_<std::allocator<void> > candata_multi;

typedef boost::shared_ptr< ::canbus::candata_multi > candata_multiPtr;
typedef boost::shared_ptr< ::canbus::candata_multi const> candata_multiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canbus::candata_multi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canbus::candata_multi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace canbus

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'canbus': ['/home/michael/Desktop/Intell_driving/ROS_Intell_Driving/src/canbus/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::canbus::candata_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus::candata_multi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus::candata_multi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus::candata_multi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::candata_multi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::candata_multi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canbus::candata_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b71a82993b1f36499df06dc83eac42a";
  }

  static const char* value(const ::canbus::candata_multi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b71a82993b1f364ULL;
  static const uint64_t static_value2 = 0x99df06dc83eac42aULL;
};

template<class ContainerAllocator>
struct DataType< ::canbus::candata_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canbus/candata_multi";
  }

  static const char* value(const ::canbus::candata_multi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canbus::candata_multi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "candata[] frame\n\
\n\
================================================================================\n\
MSG: canbus/candata\n\
uint32 id\n\
uint32 timestamp\n\
uint8[8] data\n\
";
  }

  static const char* value(const ::canbus::candata_multi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canbus::candata_multi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct candata_multi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canbus::candata_multi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canbus::candata_multi_<ContainerAllocator>& v)
  {
    s << indent << "frame[]" << std::endl;
    for (size_t i = 0; i < v.frame.size(); ++i)
    {
      s << indent << "  frame[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::canbus::candata_<ContainerAllocator> >::stream(s, indent + "    ", v.frame[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANBUS_MESSAGE_CANDATA_MULTI_H
