# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Mobileye/Mobileye_TSR_multi.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import Mobileye.msg

class Mobileye_TSR_multi(genpy.Message):
  _md5sum = "f82b8888a7d5b24d3c3ff243115b7ee5"
  _type = "Mobileye/Mobileye_TSR_multi"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Mobileye_TSR[] TSRs

================================================================================
MSG: Mobileye/Mobileye_TSR
uint8 MType
uint8 SupType
float32 PosX
float32 PosY
float32 PosZ
uint8 FilterType
"""
  __slots__ = ['TSRs']
  _slot_types = ['Mobileye/Mobileye_TSR[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TSRs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Mobileye_TSR_multi, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.TSRs is None:
        self.TSRs = []
    else:
      self.TSRs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.TSRs)
      buff.write(_struct_I.pack(length))
      for val1 in self.TSRs:
        _x = val1
        buff.write(_struct_2B3fB.pack(_x.MType, _x.SupType, _x.PosX, _x.PosY, _x.PosZ, _x.FilterType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.TSRs is None:
        self.TSRs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.TSRs = []
      for i in range(0, length):
        val1 = Mobileye.msg.Mobileye_TSR()
        _x = val1
        start = end
        end += 15
        (_x.MType, _x.SupType, _x.PosX, _x.PosY, _x.PosZ, _x.FilterType,) = _struct_2B3fB.unpack(str[start:end])
        self.TSRs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.TSRs)
      buff.write(_struct_I.pack(length))
      for val1 in self.TSRs:
        _x = val1
        buff.write(_struct_2B3fB.pack(_x.MType, _x.SupType, _x.PosX, _x.PosY, _x.PosZ, _x.FilterType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.TSRs is None:
        self.TSRs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.TSRs = []
      for i in range(0, length):
        val1 = Mobileye.msg.Mobileye_TSR()
        _x = val1
        start = end
        end += 15
        (_x.MType, _x.SupType, _x.PosX, _x.PosY, _x.PosZ, _x.FilterType,) = _struct_2B3fB.unpack(str[start:end])
        self.TSRs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B3fB = struct.Struct("<2B3fB")
