# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobileye/mobileye_LKA_Lane.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mobileye_LKA_Lane(genpy.Message):
  _md5sum = "5f536a85eb5e6c93cc0441013010300e"
  _type = "mobileye/mobileye_LKA_Lane"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 MType
uint8 Quality
uint8 Model_degree
float32 Position
float32 Curvature
float32 Heading
float32 Curvature_deriv
float32 Width
float32 View_range
"""
  __slots__ = ['MType','Quality','Model_degree','Position','Curvature','Heading','Curvature_deriv','Width','View_range']
  _slot_types = ['uint8','uint8','uint8','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       MType,Quality,Model_degree,Position,Curvature,Heading,Curvature_deriv,Width,View_range

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mobileye_LKA_Lane, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.MType is None:
        self.MType = 0
      if self.Quality is None:
        self.Quality = 0
      if self.Model_degree is None:
        self.Model_degree = 0
      if self.Position is None:
        self.Position = 0.
      if self.Curvature is None:
        self.Curvature = 0.
      if self.Heading is None:
        self.Heading = 0.
      if self.Curvature_deriv is None:
        self.Curvature_deriv = 0.
      if self.Width is None:
        self.Width = 0.
      if self.View_range is None:
        self.View_range = 0.
    else:
      self.MType = 0
      self.Quality = 0
      self.Model_degree = 0
      self.Position = 0.
      self.Curvature = 0.
      self.Heading = 0.
      self.Curvature_deriv = 0.
      self.Width = 0.
      self.View_range = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B6f.pack(_x.MType, _x.Quality, _x.Model_degree, _x.Position, _x.Curvature, _x.Heading, _x.Curvature_deriv, _x.Width, _x.View_range))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.MType, _x.Quality, _x.Model_degree, _x.Position, _x.Curvature, _x.Heading, _x.Curvature_deriv, _x.Width, _x.View_range,) = _struct_3B6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B6f.pack(_x.MType, _x.Quality, _x.Model_degree, _x.Position, _x.Curvature, _x.Heading, _x.Curvature_deriv, _x.Width, _x.View_range))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.MType, _x.Quality, _x.Model_degree, _x.Position, _x.Curvature, _x.Heading, _x.Curvature_deriv, _x.Width, _x.View_range,) = _struct_3B6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B6f = struct.Struct("<3B6f")
